name: "Python Builder"
description: "Build single file executable for python"
author: "Dhruvin Shah"
run-name: Runnig build by ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  build-linux-executable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Build package
        run: pyinstaller igen.spec

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: igen
          path: dist/igen
